name: "Release"
on:
  push:
  release:
    types:
      - published
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Setup Bun
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.1
      # Install dependencies
      - name: Install dependencies
        run: bun install
      # Build
      - name: Build
        run: bun run build
